# permissions for end users to view myapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kcontroller
    app.kubernetes.io/managed-by: kustomize
  name: myapp-viewer-role
rules:
- apiGroups:
  - myapp.example.com
  resources:
  - myapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - myapp.example.com
  resources:
  - myapps/status
  verbs:
  - get
