apiVersion: myapp.example.com/v1
kind: MyApp
metadata:
  name: myapp-sample
  namespace: default
spec:
  image: busybox
  replicas: 2
  args:
    - sleep
    - "10000"
---
apiVersion: myapp.example.com/v1
kind: MyApp
metadata:
  name: myapp-sample-2
  namespace: default
spec:
  image: busybox
  replicas: 2
  args:
    - sleep
    - "100"
---
apiVersion: myapp.example.com/v1
kind: MyApp
metadata:
  name: myapp-bad-pod
  namespace: default
  labels:
    reconciler: ignore
spec:
  image: steeling1/non-existant-image
  replicas: 3
  args:
    - sleep
    - "10000"